name: Lint and Format
on:
  pull_request:
    branches:
      - main
      - '1.0.0'
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush Build
        run: node common/scripts/install-run-rush.js build

      - name: Check linting
        run: node common/scripts/install-run-rush.js lint:check -v
